## NumPy

#### Basic Operations

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [8]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Get Dimensions of a numpy array
a.ndim


1

In [12]:
#Get Dimensions of a numpy array
c.ndim

2

In [13]:
d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [14]:
d.ndim

3

In [15]:
#Get a shape of a numpy array
a.shape

(3,)

In [16]:
b.shape

(2, 3)

In [17]:
c.shape

(3, 3)

In [18]:
a

array([1., 2., 3.])

In [19]:
a.dtype

dtype('float64')

In [20]:
a_int = np.array([1,2,3])
print(a)

[1. 2. 3.]


In [21]:
a_int.dtype

dtype('int32')

#### Accessing/Changing specific elements, rows & columns etc.

In [23]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
#Get a specific element [r,c]
a[0,3]

4

In [26]:
#Get a specific row from a numpy array

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#Get a specific column from a numpy array

a[:,0]

array([1, 8])

In [28]:
#Get a specific column from a numpy array

a[0,0]

1

In [30]:
#Change the 5th column in 1st row to 50

a[0,4] = 50

In [31]:
a

array([[ 1,  2,  3,  4, 50,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
np.full((3,3), 50, dtype='float')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [37]:
np.full((3,3), 50, dtype='int')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [43]:
np.random.rand(4,4)

array([[0.94074514, 0.84554835, 0.52164326, 0.3362127 ],
       [0.97409366, 0.15327446, 0.98703352, 0.91093673],
       [0.02380204, 0.00316521, 0.71277997, 0.26588669],
       [0.61950071, 0.93480559, 0.20091898, 0.69235252]])

In [47]:
np.random.randint(-4,4, size=(3,3))

array([[-1,  3,  2],
       [ 0,  1, -4],
       [-4,  0, -1]])

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Arithmetic Operations with NumPy - Maths + Stats

In [50]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [51]:
a+2

array([3, 4, 5, 6])

In [57]:
#DO it for -, /, *, //, ** - ALmost all the operations are satisfied

a**3

array([ 1,  8, 27, 64], dtype=int32)

In [58]:
a

array([1, 2, 3, 4])

In [59]:
a.min()

1

In [60]:
a.max()

4

In [62]:
a.mean()

2.5

In [65]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.max(a)

8

In [67]:
a.max()

8

In [68]:
np.min(a)

1

In [69]:
np.mean(a)

4.5

In [70]:
np.sum(a)

36

In [73]:
np.max(a, axis=1)

array([4, 8])

In [74]:
np.max(a, axis=0)

array([5, 6, 7, 8])

In [75]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [76]:
np.min(a, axis=1)

array([1, 5])

In [77]:
np.sum(a, axis=1)

array([10, 26])

In [78]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])